from .descriptors import DescriptorGenerator
from .descriptors import (
    MolWt,
    MolAbsCharge,
    NumHeavyAtoms,
    logP,
    TopoPSA,
    HBonds,
    RotBond,
    NumValenceElectron,
    NumMaxAbsPartialCharge,
    NumMinAbsPartialCharge,
    AromaRing,
    MolVolume,
    MorganFingerPrint,
    MACCSFingerPrint,
    BCUT,
    GetAWay,
    GetFeatureInvariants,
    USR,
    WHIM,
    MORSE,
    USRCAT,
    TopologicalTorsionFingerprint,
    MQNs,
    PEOE_VSA,
    SMR_VSA,
    SlogP_VSA,
    Autocorr2D
)
from ._sasa import SASA

AVAILABLE_DESCRIPTORS = [
    MolWt,
    MolAbsCharge,
    # NumValenceElectron,
    NumMaxAbsPartialCharge,
    NumMinAbsPartialCharge,
    RotBond,
    NumHeavyAtoms,
    # SASA,
    # logP,
    # TopoPSA,
    # HBonds,
    # AromaRing,
    # MolVolume,
    MorganFingerPrint,
    # WHIM,
    # MORSE,
    USR,
    USRCAT,
    MQNs,
    PEOE_VSA,
    # SMR_VSA,
    SlogP_VSA,
    Autocorr2D,
]
